import pdb

from models.pub import Pub
import repositories.pub_repository as pub_repository

pub_repository.delete_all()

pubs = ["Tiles Cafe Bar Bistro",
  "Cask Smugglers",
  "Malones",
  "The Abbotsford",
  "The Permit Room",
  "Thor's Tipi Bar",
  "Juniper",
  "The Dirty Martini",
  "Cask & Barrel",
  "The Register Club",
  "Hoot the Redeemer",
  "Le Monde Hotel bar",
  "Belushi's",
  "The Voodoo Rooms",
  "All Bar One",
  "El Barrio",
  "The Playfair",
  "The Doric Tavern",
  "The Hebrides",
  "Jake's Place",
  "Cafe Royal Circle Bar",
  "The Guildford Arms",
  "Palm Court",
  "bar at the Balmoral",
  "Nor'loft",
  "Kirks",
  "Milnes Bar",
  "The Three Tuns",
  "The Wash Bar",
  "Black Rose",
  "Brewhemia",
  "Jinglin' Geordie",
  "The Ark",
  "Black Bull Tavern",
  "Capital",
  "bar at The Scotsman",
  "St James Quarter bars",
  "The Ensign Ewart",
  "The Albanach",
  "Scotsman's Lounge",
  "Secret Arcade",
  "The Newsroom",
  "Nightcap",
  "Bramble",
  "Auld Hundred",
  "The Standing Order",
  "The Boozy Cow",
  "Library Bar",
  "Eastside",
  "The Thistle Street Bar",
  "Signet Library",
  "The Jolly Judge",
  "Deacon Brodie's",
  "Bunker",
  "Finnegans Wake",
  "Hanover Tap",
  "Bourbon Bar",
  "The Bow Bar",
  "Cannonball Restaurant and Bar",
  "The Inn on the Mile",
  "The Conan Doyle",
  "The Mitre",
  "The Safari Lounge",
  "Artisan Bar",
  "Kaleidoscope",
  "Kitty O'Sheas",
  "Element",
  "The Tron",
  "The Auld Reekie Tiki Bar",
  "Whiski Bar and Restaurant",
  "Sneaky Pete's",
  "The City Cafe",
  "The Globe Bar",
  "Rabble Taphouse",
  "Burgers and Beers",
  "Brewdog Cowgate",
  "Kick Ass Bar",
  "Newtown Bar",
  "Maggie Dicksons",
  "Biddy Mulligans",
  "Bar Bados",
  "The Little White Pig",
  "The Advocate",
  "The Hive",
  "The Royal Dick",
  "Three Broomsticks",
  "Whistle Binkies",
  "Royal Mile Tavern",
  "Stac Polly",
  "Malt Shovel Inn",
  "Ox184",
  "The Banshee",
  "Dropkick Murphys",
  "The Three Sisters",
  "The Pop Up Geeks",
  "Castle Arms",
  "The Last Drop",
  "Cafe Voltaire",
  "The Mash House",
  "The Kenilworth",
  "Starbar",
  "Bannermans",
  "Bierkeller",
  "Revolution",
  "Frankenstein",
  "No1 High Street",
  "The Wally Dug",
  "The Black Bull",
  "Salt Horse",
  "Tbar",
  "House of Gods",
  "The White Hart Inn",
  "Greyfriar's Bobby",
  "The World's End",
  "The Oz Bar",
  "The Basement Bar",
  "Beehive Inn",
  "The Street",
  "Bar Salsa",
  "The Piper's Rest",
  "Waterloo Bar",
  "The Booking Office",
  "Waverley Bar",
  "Pilgrim",
  "Old Bell Inn",
  "The Empress of Broughton Street",
  "The Jazz Bar",
  "Biblos",
  "Cold Town House",
  "White Horse",
  "Treacle Bar and Kitchen",
  "The Amber Rose",
  "Badger and Co",
  "The Black Cat", 
  "Twelve Picardy Place",
  "Tonic",
  "Rose Street Brewery",
  "The Royal Oak",
  "The Bier Keller",
  "Rose & Crown",
  "The Outhouse",
  "The Grapes",
  "The Fiddler's Arms",
  "Slug and Lettuce",
  "The Grassmarket Bar",
  "Candy Bar",
  "The Barony Bar",
  "The Canons' Gait",
  "The Broughton",
  "Harmonium",
  "Wee Buddha (restaurant)",
  "Bar 50",
  "The Salisbury Arms",
  "Sandy Bell's",
  "52 Canoes",
  "six°north",
  "Pickles",
  "The Wild Yarrow",
  "The Bristo Bar",
  "Captain's Bar",
  "Paradise Palms",
  "The Holyrood 9A",
  "McSorleys Irish Bar",
  "127",
  "The Brass Monkey",
  "The Mercat Bar and Kitchen",
  "Scotch Hop",
  "Swanys",
  "Fierce Bar",
  "The Theatre Royal Bar",
  "The Chaumer",
  "Dragonfly",
  "Rose Theatre Cafe",
  "The Cumberland Bar",
  "The Doctors Bar",
  "The Wee Red Bar",
  "Alexander Graham Bell",
  "Dirty Dicks",
  "The Cambridge Bar",
  "Planet",
  "George Street Bar",
  "Scotts of Rose Street",
  "Kay's Bar",
  "The Tolbooth Tavern",
  "Panda and Sons",
  "Jeanie Deans",
  "Teviot",
  "Soul Nation",
  "Jeremiahs Taproom",
  "Pleasance",
  "Red Squirrel",
  "Clark's Bar",
  "Angel's Share",
  "The Huxley",
  "The Blue Blazer",
  "Edinburgh Gin Distillery",
  "Uno Mas",
  "Usquabae",
  "CC Blooms",
  "4042",
  "Caley Picture House",
  "Innis and Gunn taproom",
  "Ryan's Cellar Bar",
  "Heads and Tales",
  "Ghillie Dhu",
  "The Caley Bar",
  "Eden Mill Gin House",
  "Apothecary",
  "Joseph Pearce's",
  "Footlights",
  "Hey Palu",
  "The Chanter",
  "Brewdog Lothian",
  "The Southsider",
  "The Devil's Cut",
  "All Bar One",
  "The Antiquery",
  "Shakespeare",
  "The Pear Tree",
  "Indigo Yard",
  "The Kilderkin",
  "Hemma",
  "Filmhouse Cafe Bar",
  "The Last Word Saloon",
  "Bailie Bar",
  "Smithies Ale House",
  "Brauhaus",
  "Velveteen",
  "56 North",
  "The Hanging Bat",
  "The Joker and the Thief",
  "Henry's Cellar Bar",
  "The Windsor",
  "The Raging Bull",
  "RT's Bar",
  "Moriarty",
  "Lebowskis",
  "Greenmantle",
  "O'Connor's",
  "Monboddo BAr",
  "Sky Bar",
  "Mathers Bar",
  "Hamilton's Bar and Kitchen",
  "One Canonmills",
  "The Ventoux",
  "Au Bar",
  "The Cloisters",
  "First Fleet",
  "Sofi's Southsise",
  "The Green Room",
  "Teuchters",
  "Hector's",
  "Crosstwon Eatery",
  "Stockbridge Tap",
  "The Dog House",
  "The Ale House",
  "Burlington Bros",
  "The Auld Hoose",
  "St Bernards Bar",
  "Bar Luna",
  "Priscillas",
  "The Cuckoos Nest",
  "The Orchard",
  "Hare of the Dog",
  "International Bar",
  "Bennets Bar",
  "The Oxford Bar",
  "Thomsons Bar",
  "Halfway House",
  "The Black Fox",
  "Froth and Flame",
  "Akva",
  "Platform 5",
  "Shandwicks",
  "Drouthy Neighbors",
  "The Tourmalet",
  "Athletic Arms",
  "The Regent",
  "The Blackbird",
  "Holyrood Distillery",
  "Monty's",
  "The High Dive",
  "The Mad Hatter",
  "Henricks Bar",
  "Robbies Bar",
  "The Southern",
  "The Jolly Botanist",
  "The Golf Tavern",
  "Southside scran",
  "Marcos Pool Hall",
  "Cellar Monkey",
  "The Haymarket",
  "The Bier Hoose",
  "The Artisan",
  "Earl of Marchmont",
  "The Mash Tun",]

for pub in pubs:
  pub_object = Pub(pub)
  pub_repository.save(pub_object)

pdb.set_trace()